<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Life</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Welcome to My Life</h1>
    </header>

    <nav>
        <ul>
            <li><a href="#about">About Me</a></li>
            <li><a href="#hobbies">Hobbies</a></li>
            <li><a href="#contact">Contact Me</a></li>
        </ul>
    </nav>

    <section id="about">
        <h2>About Me</h2>
        <p>Hello! I'm [Your Name], and this is my personal website. Here, you will learn more about my life, my hobbies, and how to contact me.</p>
    </section>

    <section id="hobbies">
        <h2>My Hobbies</h2>
        <ul>
            <li>Traveling</li>
            <li>Reading</li>
            <li>Playing Football</li>
            <li>Coding</li>
        </ul>
    </section>

    <section id="contact">
        <h2>Contact Me</h2>
        <form id="contactForm">
            <label for="name">Your Name:</label>
            <input type="text" id="name" required><br>

            <label for="email">Your Email:</label>
            <input type="email" id="email" required><br>

            <label for="message">Your Message:</label>
            <textarea id="message" required></textarea><br>

            <button type="submit">Submit</button>
        </form>
    </section>

    <footer>
        <p>&copy; 2024 My Life | All Rights Reserved</p>
    </footer>

    <script src="script.js"></script>
</body>
</html>
